# Generated by Django 5.2.10 on 2026-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('clas', models.PositiveIntegerField()),
                ('roll', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('guard', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('student_img', models.ImageField(blank=True, null=True, upload_to='student_faces/')),
                ('last_present', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
