# Generated by Django 5.2.10 on 2026-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_present',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
    ]
